on:
  workflow_dispatch:
    inputs:
      appName:
        type: choice
        description: Microservice Spring Name.
        required: true
        options:
          - a0
          - a6
          - a9
          - api-gateway
          - corp-cancel-port-out
          - corp-port-out-pre-validate
          - corp-prep-req-pin
          - corp-req-pin
          - online-query
          - p0
          - p1
          - p2
          - p3
          - p4
          - p5
          - p6
          - p7
          - p9
          - port-deact-fwd
          - port-deact
          - port-in-cancel
          - port-in-req
          - port-out-resp
          - port-validation
          - r0
          - r6
          - r7
          - r9
          - res-cancel-port-out
          - res-req-pin
      # use-emoji:
      #   type: boolean
      #   description: Include 🎉🤣 emojis
      config:
        type: boolean
        description: 🎉Update Environment variables
      redis:
        type: boolean
        description: 🎉Create Connector Cache for Redis
      mongodb:
        type: boolean
        description: 🎉Create Connector Cosmos DB🎉
      keyVault:
        type: boolean
        description: 🎉Create Connector Key Vault
      storageBlob:
        type: boolean
        description: 🎉Create Connector Storage - Blob
      # environment2:
      #   type: environment

env:
  isConfig: ${{ github.event.inputs.config }}
  isRedis: ${{ github.event.inputs.redis }}
  isMongodb: ${{ github.event.inputs.mongodb }}
  isKeyVault: ${{ github.event.inputs.keyVault }}
  isStorageBlob: ${{ github.event.inputs.storageBlob }}

jobs:
  deploy:
    name: prd-${{ github.event.inputs.appName }}
    runs-on: ubuntu-latest
    steps:
      # - name: Login via Azure CLI
      #   shell: bash
      #   run: |
      #     az login --identity --username ${{ secrets.AZURE_SELFHOST_USER_MANAGE_IDENTITY_CLIENT_ID }}
      #     az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     az config set extension.use_dynamic_install=yes_without_prompt
      #     az extension add -n spring -y

      - name: Convert json to env variable files
        if: (env.isConfig == 'true')
        shell: bash
        run: echo Convert json to env variable files

      - name: Deploy update config env to Azure Spring App
        if: (env.isConfig == 'true')
        shell: bash
        run: echo Deploy update config env to Azure Spring App

      - name: Deploy Service Connector Cosmos DB
        if: (env.isMongodb == 'true')
        shell: bash
        run: echo "Deploy Service Connector Cosmos DB"

      - name: Deploy Service Connector Cache for Redis
        if: (env.isRedis == 'true')
        shell: bash
        run: echo "Deploy Service Connector Cache for Redis"

      - name: Deploy Service Connector Key Vault
        if: (env.isKeyVault == 'true')
        shell: bash
        run: echo "Deploy Service Connector Key Vault"

      - name: Deploy Service Connector Storage - Blob
        if: (env.isStorageBlob == 'true')
        shell: bash
        run: echo "Deploy Service Connector Storage - Blob"
